Security configured
IvanLuchkin/hibernate-cinema pull request #12
Opened 2021-02-20 22:03 UTC by IvanLuchkin

- UserDetailsService implemented
- Endpoint access configuraion added
- Database authentication set up
- Roles added

2021-02-21 11:47 UTC, YuraMitriakhin approved these changes
good job

2021-02-22 08:10 UTC, RomanDubovskyi requested changes

2021-02-22 08:10 UTC, RomanDubovskyi commented on src/main/java/cinema/controller/InjectController.java
> +public class InjectController {
```suggestion
@Component
public class DataInitializer {
```
it's not quite controller

2021-02-22 08:10 UTC, RomanDubovskyi commented on src/main/java/cinema/model/Role.java
> +    private RoleName roleName;
user Long id for PK 
with your current impl it'll be more complicated if your want to update RoleName, etc

2021-02-22 09:04 UTC, RomanDubovskyi approved these changes

2021-02-22 09:51 UTC, merged